#!/bin/sh
set -e

STASH=$(git stash --include-untracked --quiet --keep-index || echo "stash failed")
trap '[ "$STASH" = "stash failed" ] || git stash pop --quiet' EXIT

UNFORMATTED=$(gofmt -l .)
if [ -n "$UNFORMATTED" ]; then
  echo "go fmt needs to fix these files:"
  echo "$UNFORMATTED"
  echo "run: go fmt ./..."
  exit 1
fi

go vet ./...
go build ./...
