name: Auto-merge

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  enable-auto-merge:
    if: github.event.pull_request.user.login == 'wingnut128' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - run: gh pr merge --repo "$REPO" "$PR_NUMBER" --auto --rebase
        env:
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
